### ISSUE TITLE
Metadata Filter Capability

### ISSUE THREAD

**Issue by krpapadopoulos** [spotify/voyager#33]
Could vectors be added with metadata to support metadata filtered ANN search?

Curious how this may be handled with the existing implementation other than creating indices for different metadata categories?

**Comment by markkohdev** [comment]
Hey @krpapadopoulos, sorry about losing track of this issue -- we're setting up some structure so that we respond to things in a more timely manner going forward.
We have definitely discussed implementing metadata filter support but it's a pretty large undertaking that we unfortunately don't have time to work on at the moment.  We are definitely open to contribution of this feature if you or anyone else would like to take it on!

I'm currently working on an implementation of [`StringIndex` in core](#11) which will hopefully lay some groundwork for metadata support.

When discussing how we might implement this, we proposed a solution along the following lines:
- Metadata associated with each item would be passed in a parallel array to the items during `addItems`, or added to an item at a later time with a dedicated message
- During query time, the algorithm would take any metadata filter values and skip over any items in the deepest index level which don't satisfy the filter criteria (Note: this will have runtime performance impact due to passing over values)
- Metadata/labels would likely be stored in the [index Metadata](https://github.com/spotify/voyager/blob/main/cpp/Metadata.h) in the core library
- These metadata categories would get written out to the index file as binary POD and then loaded during index load

Happy to discuss this more with anyone willing to take it on!

**Comment by davidbernat** [comment]
@markkohdev @krpapadopoulos I came here to say this. In truth, all that would be needed is a mask input that restricts which ids are eligible for nearest neighbor search. It is a killer feature that directly bests broader competitors. Chroma, for instance, handles metadata support, but in most cases metadata is either a small feature set of a problem, and so can be handled by a simple dictionary lookup equivalent, or substantial enough that large databases like Meilisearch are queried. The only feature that Voyager needs to replace Chroma in a raw dev stack is that ability to mask out ids that have been determined violating from an external metadata query. And that, a mask, ought to be able to be implemented pretty deeply in the core of the algorithm in Voyager, and probably exists in the original papers as a use case, so no speed or bloat would need to be compromised. It would completely remove dependency on a lot of stack in the era of querying for AI input models. Want to chat about implementing this? I am a pretty mathy post-physicist engineer and I have not been completely turned off by Spotify yet.
