### ISSUE TITLE
Index 'ef' is lost in index loading

### ISSUE THREAD

**Issue by cvillela** [spotify/voyager#57]
`voyager = 2.0.2`

When constructing an index, assigning an "ef" value to it for querying and saving the index to a file with the "save", more especifically:
 `save(file_like: BinaryIO)`

The "ef" parameter gets reset to default when loading an Index from that file by `index = Index.load(file_obj)`

ex:

```
index = Index(
    space,
    M=M,
    ef_construction=ef_construction,
    random_seed=random_seed,
)
ids = index.add_items(embbedings, ids)
index.ef = 200
print(index.ef) # ---> 200
io_index = io.BytesIO()
index.save(io_index)

index = Index.load(io_index)
print(index.ef) #---> 10
```

**Comment by markkohdev** [comment]
Hey @cvillela, this is indeed a valid issue.  We will fix this, but note that we are planning to deprecate this parameter in the future.  Having a `ef` parameter for the index to use as a default `query_ef` is slightly dangerous because `ef` can not be smaller than the number of neighbors (`k`) requested.  Instead of this instance level parameter, we will likely update the behavior of `.query()` to set the `ef` equal to `k` if `query_ef` isn't passed.

Because of this, I would recommend against using this parameter and instead pass `query_ef` explicitly to each `query` call, even if it's just simulating the behavior mentioned above.

Happy to hear any thoughts on the above though!
